<?php

namespace Carpet\Bundle\PetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GadgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GadgetRepository extends EntityRepository
{
}
