carpet_admin:
    resource: "@CarpetAdminBundle/Controller/"
    type:     annotation
    prefix:   /

carpet_pet:
    resource: "@CarpetPetBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin