admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
# app/config/routing.yml
acme_hello:
    type: rest
    resource: "@CarpetPetBundle/Resources/config/pets_routes.yml"